### ISSUE TITLE
Pressing Enter on Bluetooth keyboard does not submit review

### ISSUE THREAD

**Issue by LiquidFire** [xiprox/WaniKani-for-Android#22]
I'm using the app on a Pixel C with its physical keyboard (which connects as a Bluetooth keyboard). When I type an answer to a review and press Enter on the keyboard, nothing happens. I have to press the submit button on the touchscreen to move on to the next review. This is very inconvenient as you have to take your hands off the keyboard every couple of seconds and hit a tiny button on the touchscreen.

When doing reviews through the WaniKani website on Firefox the Enter button works correctly.

**Comment by xiprox** [comment]
Hello,

I understand the inconvenience of this, definitely. I'd hate it myself. However, the sections around reviewing were taken from the WaniKani Mobile project (with permission). I have no idea how things worked after all this time.

As I previously noted here and elsewhere too, I'm not actively working on this project. It's been quite a time since I last did something significant too. I do have hopes to get back to it and put it in a decent state, but please don't expect anything.

**Comment by LiquidFire** [comment]
Hi,

Thanks for the update. I understand you're not actively working on the app anymore. I definitely didn't post this issue with the expectation that you would fix it.

In fact, other than this issue the app works pretty well on the Pixel C, so I will actually try to fix this myself and submit a patch, because I really want to be able to do my reviews on the tablet. (Again, it's fine if you don't have time to merge or look at the patch when it's done)

**Comment by xiprox** [comment]
I see. Well, I *should* be able to look into and merge a single fix patch. Nice to hear that you are enjoying it!
