### ISSUE TITLE
Typing cyu comes out しゅ (syu)

### ISSUE THREAD

**Issue by Emrayla** [xiprox/WaniKani-for-Android#26]
Think it's the same for cyo -> syo.

**Comment by xiprox** [comment]
Hello,

Can you elaborate a bit on the issue, please?

And well, neither cyu not syu are valid sounds, I believe. Do you mean something like tsyu, perhaps? Have you tried that? You would also read しゅ as shyu.

**Comment by Emrayla** [comment]
Cyu is normally the shortcut for typing chi followed by small yu (ちゅ).  Cyo would be ちょ (chyo).

**Comment by xiprox** [comment]
I see. Wouldn't ちゅ be read as chu and ちょbe read as cho though? Why not simply go ahead and type the way they are read?

And well, ultimately, as a response to this specific issue, there are multiple reasons for which I won't be working on this:
1. I  can't see how skipping a single letter can be called a shortcut. It really doesn't look like it would save enough time to be called one. (And if you were to just write the way they are actually read, it'd be going down to three letters to begin with.)
2. While typing readings, you kinda read them in your brain. I'd imagine typing cyo (or chyo) instead of cho could possibly make you get used to a wrong reading. (Yet another reason to just type exactly as they are read!)
3. Again, as I said here and elsewhere, I'm not actively working on this project. Even if the above points were to be justified, I doubt I'd be acting for something as trivial as this anytime soon.

**Comment by Emrayla** [comment]
I hit this issue ALL the time because for those of us who've typed Japanese alot, it gets programmed into your brain just like touch typing. So I'm constantly typing cyo, cya, cyu, and then when the result is wrong having to back up and type chyo, chya, chyu very intentionally. I say it with the ch in my brain automatically.

Do you know if anyone is actively working on a WaniKani Android app?

**Comment by xiprox** [comment]
I see. But again, I'm no longer active on this so...

And nope, this is the only Android app that is still "alive". I do hope to get back to it and do a proper rewrite though. So you might eventually get this in. 

And really, it really doesn't sound all that hard or deal-breaking to just switch to "cho" or "shu" or "chu" or "shu". In fact, it sounds like less effort than having to figure (although possibly automatically) in your brain that the c comes from the chi and the yo is what makes it cho... I mean, read it? cho. Type it? cyo. Why even? Why not just cho and cho?
