### ISSUE TITLE
Crash when going from vertical to horizontal view.

### ISSUE THREAD

**Issue by lasrod** [xiprox/WaniKani-for-Android#5]
I tried to find the bug in the code but I'm too new to android development to fully understand how to debug this properly.

Either way... The crash happens 9 of 10 times if you:
1. Start the app vertically.
2. Let the application do it's update. 
3. Scroll down the page a little bit.
4. Rotate to horizontal view.
5. Crashes.

I can reproduce the crash in Android Studio as well as on the phone.

**Comment by xiprox** [comment]
I tried to reproduce this just now and I it seems to be caused by too many AsyncTasks being executed at once. The app is more likely to crash if you flip the screen *while* the content is being updated though. As for a fix, we could execute the tasks one by one instead of all at once. If we do that though, it's going to take longer to get all the data. I'll have to see about this.
