### ISSUE TITLE
Last entered lesson input remains for the next lesson

### ISSUE THREAD

**Issue by chooban** [xiprox/WaniKani-for-Android#65]
There appears to be a bug with the latest version of WK.

**Issue**
On second and subsequent lesson blocks, the last answer from the previous lesson is present in the input field.

**Steps To Reproduce**
Create a scenario where the app will offer to continue to the next set of lessons. Complete the first set, and then go directly to the second set. The text from the last lesson will be present in the input field.

I'm using v1.2.6 on a OnePlus 3T running OxygenOS 4.5.1 and Android 7.1.1

**Comment by xiprox** [comment]
Hello.

This was fixed in #61 and I'll hopefully be publishing an update in the coming weeks.

If you'd like, however, you can [join the alpha channel](https://github.com/xiprox/WaniKani-for-Android#alpha-testing) on the Play Store, to receive the fix now. Please keep in mind that the alpha channel basically reflects the latest state of this repository and it may at times be extremely unstable or even broken.

**Comment by chooban** [comment]
Fantastic, thanks!
